// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230630100529_seed-customer")]
    partial class seedcustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "admin",
                            Password = "admin",
                            Role = 1
                        },
                        new
                        {
                            Username = "staff",
                            Password = "staff",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Repository.Entities.Address", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("City");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            City = "Ho Chi Minh",
                            Street = "Bui Vien"
                        },
                        new
                        {
                            City = "Ha Noi",
                            Street = "Tran Duy Hung"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddressCity");

                    b.HasIndex("PressId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = new Guid("925823c7-b48a-44fb-9d57-b4e58165fdf6"),
                            AddressCity = "Ho Chi Minh",
                            Author = "Aristotle",
                            ISBN = "978-3-16-148410-0",
                            PressId = new Guid("66cc1f7d-97f3-4ec7-9423-0ef2c75cb914"),
                            Price = 100000.0,
                            Title = "Philosophy"
                        },
                        new
                        {
                            ID = new Guid("b2c9e028-3ca6-494c-8030-378c8999e9a6"),
                            AddressCity = "Ho Chi Minh",
                            Author = "Einstein",
                            ISBN = "978-3-16-148410-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 200000.0,
                            Title = "Physics"
                        },
                        new
                        {
                            ID = new Guid("88316682-e17d-48d4-808d-c703182f5a89"),
                            AddressCity = "Ha Noi",
                            Author = "Aristotle",
                            ISBN = "978-3-16-148410-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 150000.0,
                            Title = "Science Fiction"
                        },
                        new
                        {
                            ID = new Guid("701629b1-8da3-466f-9918-e850956fb911"),
                            AddressCity = "Ha Noi",
                            Author = "Aristotle",
                            ISBN = "978-3-16-148410-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 150000.0,
                            Title = "Science Fiction"
                        },
                        new
                        {
                            ID = new Guid("d8300ac5-7ac5-4ca1-9d20-87fa34980af1"),
                            AddressCity = "Ha Noi",
                            Author = "Stella Blackwood",
                            ISBN = "978-1-23-456789-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 87500.0,
                            Title = "The Galactic Voyage"
                        },
                        new
                        {
                            ID = new Guid("65f7d88c-d1ea-4a42-8ff4-4c3e1f3bade2"),
                            AddressCity = "Ha Noi",
                            Author = "Nathan Greenfield",
                            ISBN = "978-9-87-654321-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 203750.0,
                            Title = "Time Rift Chronicles"
                        },
                        new
                        {
                            ID = new Guid("9d8c7115-89cc-47f8-980f-ffb02a8de248"),
                            AddressCity = "Ha Noi",
                            Author = "Erika Silverstone",
                            ISBN = "978-5-55-555555-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 121250.0,
                            Title = "Cybernetic Dreams"
                        },
                        new
                        {
                            ID = new Guid("a088fbfa-a0e3-4762-9fd4-80be40162175"),
                            AddressCity = "Ha Noi",
                            Author = "Oliver Armstrong",
                            ISBN = "978-2-22-333333-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 185900.0,
                            Title = "Quantum Paradox"
                        },
                        new
                        {
                            ID = new Guid("c0e10b86-80e4-40b6-9e6b-2a761df7525e"),
                            AddressCity = "Ha Noi",
                            Author = "Maya Thompson",
                            ISBN = "978-0-98-765432-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 92800.0,
                            Title = "Stellar Convergence"
                        },
                        new
                        {
                            ID = new Guid("df9dd9c9-8a09-477b-bbe9-4860b2cbc89e"),
                            AddressCity = "Ha Noi",
                            Author = "Benjamin Hartman",
                            ISBN = "978-7-77-777777-0",
                            PressId = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Price = 176300.0,
                            Title = "Galactic Empire"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Press", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Presses");

                    b.HasData(
                        new
                        {
                            ID = new Guid("66cc1f7d-97f3-4ec7-9423-0ef2c75cb914"),
                            Category = 2,
                            Name = "E Book"
                        },
                        new
                        {
                            ID = new Guid("d75cefaf-2361-4251-a2ff-6cbe36182899"),
                            Category = 1,
                            Name = "Magazine"
                        },
                        new
                        {
                            ID = new Guid("949707e7-ec5c-43b0-9d50-669a067d584f"),
                            Category = 0,
                            Name = "Book"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Book", b =>
                {
                    b.HasOne("Repository.Entities.Address", "Address")
                        .WithMany("Books")
                        .HasForeignKey("AddressCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Press", "Press")
                        .WithMany("Books")
                        .HasForeignKey("PressId");

                    b.Navigation("Address");

                    b.Navigation("Press");
                });

            modelBuilder.Entity("Repository.Entities.Address", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Repository.Entities.Press", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
